/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegio;

import java.util.HashSet;
import javax.swing.JFrame;
public class Colegio1 extends javax.swing.JFrame {


    public static HashSet<Alumno> alumno = new HashSet<>();
    public static HashSet<Materia> materia = new HashSet<>();
    
    public Colegio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AlumnoMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MateriaMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        InscripcionMenu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        AlumnosInscriptosMenu = new javax.swing.JMenuItem();
        SalirEscritorio = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INSCRIPCION");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        AlumnoMenu.setText("Agregar Alumno");
        AlumnoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnoMenuActionPerformed(evt);
            }
        });
        jMenu1.add(AlumnoMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        MateriaMenu.setText("Agregar Materia");
        MateriaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriaMenuActionPerformed(evt);
            }
        });
        jMenu2.add(MateriaMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Registro");

        InscripcionMenu.setText("Inscripciones");
        InscripcionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscripcionMenuActionPerformed(evt);
            }
        });
        jMenu3.add(InscripcionMenu);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Alumnos Inscriptos");

        AlumnosInscriptosMenu.setText("Inscriptos");
        AlumnosInscriptosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnosInscriptosMenuActionPerformed(evt);
            }
        });
        jMenu5.add(AlumnosInscriptosMenu);

        jMenuBar1.add(jMenu5);

        SalirEscritorio.setText("Salir");
        SalirEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirEscritorioActionPerformed(evt);
            }
        });
        jMenuBar1.add(SalirEscritorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnoMenuActionPerformed
        FormularioAlumno formA = new FormularioAlumno(alumno);
        Escritorio.add(formA);
        formA.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_AlumnoMenuActionPerformed

    private void SalirEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirEscritorioActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirEscritorioActionPerformed

    private void MateriaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaMenuActionPerformed
        FormularioMateria formM = new FormularioMateria(materia);
        Escritorio.add(formM);
        formM.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_MateriaMenuActionPerformed

    private void InscripcionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionMenuActionPerformed
        Registros regi = new Registros();
        Escritorio.add(regi);
        regi.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_InscripcionMenuActionPerformed

    private void AlumnosInscriptosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnosInscriptosMenuActionPerformed
        AlumnosInscriptos ai = new AlumnosInscriptos();
        Escritorio.add(ai);
        ai.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_AlumnosInscriptosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlumnoMenu;
    private javax.swing.JMenuItem AlumnosInscriptosMenu;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem InscripcionMenu;
    private javax.swing.JMenuItem MateriaMenu;
    private javax.swing.JMenu SalirEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
